/*
 * Copyright (c) 2026 INDEX0 AI Inc. All Rights Reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL CODE.
 * NOTICE: All information contained herein is, and remains the property of INDEX0 AI Inc.
 * The intellectual and technical concepts contained herein are proprietary to INDEX0 AI Inc.
 * and may be covered by U.S. and Foreign Patents, patents in process, and are protected by
 * trade secret or copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained from INDEX0 AI Inc.
 */

"use client";

import React from "react";
import Link from "next/link";
import { IconShieldLock, IconFileText } from "@tabler/icons-react";

export default function TermsPage() {
  return (
    <main className="min-h-[100dvh] w-full max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-12">
      {/* Header */}
      <div className="space-y-3 border-oklab-b pb-8">
        <div className="inline-flex items-center gap-2 text-xs font-mono text-[var(--accent)] font-semibold uppercase tracking-wider">
          <IconFileText size={16} />
          <span>[LEGAL DISCLOSURE: TERMS OF SERVICE]</span>
        </div>
        <h1 className="font-display-section text-[var(--fg)]">
          Terms of Service &amp; Licensing Bounds.
        </h1>
        <div className="text-xs font-mono text-[var(--meta)]">
          LAST MODIFIED: SEPTEMBER 18, 2026 • EFFECTIVE IMMEDIATELY
        </div>
      </div>

      {/* Proprietary Notice Box */}
      <div className="p-6 rounded-2xl border-oklab bg-[var(--surface-warm)] font-mono text-xs text-[var(--fg)] space-y-3 leading-relaxed">
        <div className="flex items-center gap-2 text-[var(--accent)] font-bold">
          <IconShieldLock size={16} />
          <span>PROPRIETARY &amp; CONFIDENTIAL NOTICE</span>
        </div>
        <p>
          Copyright (c) 2026 INDEX0 AI Inc. All Rights Reserved. All proprietary software, algorithms, WebGL shader pipelines, and agent orchestration engines accessible via ai.index0.in remain the exclusive intellectual property of INDEX0 AI Inc.
        </p>
      </div>

      {/* Terms Sections */}
      <div className="space-y-8 font-editorial text-base leading-relaxed text-[var(--fg)]">
        <section className="space-y-3">
          <h2 className="font-mono font-bold text-xl text-[var(--fg)]">
            1. Scope of Sovereign Deployment
          </h2>
          <p>
            INDEX0 grants enterprise and community licensees the right to deploy INDEX0 agent instances within their self-hosted or dedicated VPC environments. You retain 100% sovereign ownership of all source code, AST patches, test assertions, and data models generated by or processed through the platform.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-mono font-bold text-xl text-[var(--fg)]">
            2. Copyleft &amp; Open-Source Isolation Boundary
          </h2>
          <p>
            INDEX0 isolates third-party open-source components (including Lago rating engines, PostgreSQL databases, and OpenMeter telemetry daemons) inside separate network-isolated container enclaves. Communication occurs strictly over standard REST and gRPC API channels. No copyleft (GPL/AGPL) code is statically linked or incorporated into the closed-source proprietary codebase.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-mono font-bold text-xl text-[var(--fg)]">
            3. Zero Data Retention SLA
          </h2>
          <p>
            INDEX0 AI Inc. commits to zero data retention of customer source code, AST trees, or prompt streams on any multi-tenant server infrastructure. Ephemeral microVM instances are securely purged from memory upon session termination.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-mono font-bold text-xl text-[var(--fg)]">
            4. Service Level Commitments
          </h2>
          <p>
            For Sovereign Enterprise license holders, INDEX0 guarantees 99.99% cluster availability across dedicated VPC nodes with sub-millisecond telemetry synchronization.
          </p>
        </section>
      </div>

      {/* Footer Navigation */}
      <div className="pt-8 border-oklab-t flex items-center justify-between font-mono text-xs text-[var(--meta)]">
        <Link href="/privacy" className="text-[var(--accent)] hover:underline">
          View Privacy &amp; Data Policy →
        </Link>
        <span>INDEX0 LEGAL REF: ID-2026-TOS-V2</span>
      </div>
    </main>
  );
}
